### PR TITLE
Fetch single recipe

### PR DESCRIPTION
**Pull request by ryanbahan**
### Where should the reviewer start?

Testing the DOM and checking the functionality within DOM updates. Code isn't the cleanest, but am certainly planning to red - green - refactor here and likely break the DOM HTML out into individual components once all the fetches are sorted out.

### Any background context you want to provide?

The favorite button doesn't yet have functionality.

### Screenshots (if appropriate)

### CODE REVIEW

**Comment by melissasteele09** [comment]
looks great!

**Comment by melissasteele09** [comment]
This looks great. Id love some clarification on the use of "await" when fetching data as opposed to ".then"

**Comment by melissasteele09** [comment]
This looks great. Id love some clarification on the use of "await" when fetching data as opposed to .then()..does this prevent you from using a catch?

**Comment by ryanbahan** [comment]
@melissasteele09 You can still use catch() with await and we'll need to add those in. Await is essentially just "syntactic sugar" for then() - they do the same thing.

**Pull request merged**
