### PR TITLE
ISSUE: Post request on grocery item 'checkout' doesn't update on first click

### PR DESCRIPTION
**Pull request by ryanbahan**
Issue: When clicking the 'checkout' button on the grocery list modal, the actual user pantry doesn't seem to be updated until the second time a user opens the modal and clicks checkout. 

The first time around, the server responds with ""X units of item # XXXXX were added to user XX's pantry'", but the user's pantry doesn't seem to be updated.

The second time around, the server responds with ""User # XX has X units of item # XXXXX" and then the pantry seems to be updated and function as normal.

Fetch requests are being made via the databaseController class, which is being called within the domUpdates class/groceryModalCheckout() method. Console logs are in place to document the behavior.

### CODE REVIEW

**Comment by ryanbahan** [comment]
@khalidwilliams Are you able to take a look at this? I can't wrap my head around once going on/don't know exactly how to test this/don't want to mess with the database too much.

**Comment by ryanbahan** [comment]
This update now mostly works, but some items just don't seem to update on certain users.

**Comment by ryanbahan** [comment]
Seems to behave more inconsistently when many items are added. Database seems to be working, but the code to refresh the user's pantry visa new fetch also seems to be working. Worried about testing any further since we're continually adding items to the server.

**Comment by khalidwilliams** [comment]
@ryanbahan @melissasteele09 @ERaith heads up, I found a strange bug in `Pantry.getIngredientsNeeded`. If you make an update to the server with the Checkout button in the modal, then add that recipe again and keep pressing 'Grocery List' (without checking out), every time you reopen the grocery list, the quantity and amount keeps incrementing. It has something to do with your duplication removal in the Pantry class, seems like you continue to increment the `quantity` property on a User's saved recipes (The issue is happening somewhere `Pantry line 30`. See if you can get to the bottom of the bug!

**Comment by ryanbahan** [comment]
@khalidwilliams the issue is that the grocery list doesn't seem to consistently update properly. We're re-fetching the user's pantry when the grocery modal is closed, so it *should* mean that when you re-open the grocery list, it is empty (since you just bought all your ingredients).

Most of the time, this is true. However *sometimes* random ingredients just never update on the grocery list, and are stuck there forever - even when the database returns a success/none of the methods break/everything seems to be functioning as intended.

**Comment by ryanbahan** [comment]
@khalidwilliams looks like we posted at the same time, I think we are talking about the same thing. Thank you!

**Pull request closed without merging**
